### ISSUE TITLE
Interessado nesse plugin! Precisa de ajuda para publicar?

### ISSUE THREAD

**Issue by raphaklaus** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#1]
:) Gostaria de saber no que precisa ajuda para publicar ou desenvolver esse plugin. Tenho interesse nele.

Mantenha o bom trabalho! 
Abraços

**Comment by Luc45** [comment]
E aí meu amigo, tudo bom?

O plugin está em fase de aprovação pelo pessoal do WordPress, não deve ser
problema ;)

No entanto, se ainda assim quiser contribuir com melhorias, são sempre bem
vindas!

Abraços!!

Em 17 de mar de 2018 22:40, "Raphael D. Pinheiro" <notifications@github.com>
escreveu:

**Comment by Luc45** [comment]
Plugin publicado! 

https://br.wordpress.org/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto

**Comment by raphaklaus** [comment]
Boa!! Parabéns pelo trabalho! Vai ajudar muita gente :)

PHP não é meu forte, mas se precisar de algo e não tiver mãos pra isso, tenta me citar em alguma issue aqui.

Abraços
