### ISSUE TITLE
I would like remove the small button

### ISSUE THREAD

**Issue by Guischweizer** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#15]
Hey, I would like to remove this small button but I don't know how to do it nether if I could do that. Please if you have any way let me know! Thanks, guys 😄 
![image](https://user-images.githubusercontent.com/37005757/69101449-69f2ee80-0a3e-11ea-95cf-4b32bbc89f5a.png)

**Comment by Luc45** [comment]
Yes, just hide it with CSS.

Em seg, 18 de nov de 2019 20:08, Guilherme Schweizer <
notifications@github.com> escreveu:

**Comment by Guischweizer** [comment]
Cool, I thought we had a button or something like that inside Wordpress but I'll use your suggestion! 
Thanks
