### ISSUE TITLE
Erro 500 ao instalar plugin

### ISSUE THREAD

**Issue by raphaklaus** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#2]
Opa! Acabei de instalar o plugin e após isso todo o site está dando erro 500.

Meu site usa HTTPS.

**Comment by Luc45** [comment]
Amigo, coloca isso no functions.php e me fala o que aparece:
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

**Comment by raphaklaus** [comment]
Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /var/www/html/wp-content/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto/includes/class-woocommerce-correios-calculo-de-frete-na-pagina-do-produto.php:251 Stack trace: #0 /var/www/html/wp-content/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto/includes/class-woocommerce-correios-calculo-de-frete-na-pagina-do-produto.php(111): Woocommerce_Correios_Calculo_De_Frete_Na_Pagina_Do_Produto->check_woocommerce() #1 /var/www/html/wp-content/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto/woocommerce-correios-calculo-de-frete-na-pagina-do-produto.php(77): Woocommerce_Correios_Calculo_De_Frete_Na_Pagina_Do_Produto->__construct() #2 /var/www/html/wp-content/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto/woocommerce-correios-calculo-de-frete-na-pagina-do-produto.php(81): run_woocommerce_correios_calculo_de_frete_na_pagina_do_produto() #3 /var/www/html/wp-settings.php(305): include_once('/var/www/html/w...') #4 /va in /var/www/html/wp-content/plugins/woo-correios-calculo-de-frete-na-pagina-do-produto/includes/class-woocommerce-correios-calculo-de-frete-na-pagina-do-produto.php on line 251

**Comment by Luc45** [comment]
Arrumado, plugin atualizado... Em breve deve aparecer pra você a atualização pra versão 1.3.2 que resolve isso. Geralmente o WordPress desabilita automaticamente o plugin quando ele causa erro 500, mas se isso não acontecer, desinstale o plugin via FTP deletando a pasta e instalando a versão 1.3.2 novamente, tranquilo?

**Comment by Luc45** [comment]
No WordPress demora um pouco pro plugin atualizar, você pode baixar o zip direto aqui do Git se preferir, é exatamente o mesmo código.

**Comment by Luc45** [comment]
O update já está disponível lá no repositório do WordPress, me avisa se resolveu ;)

**Comment by raphaklaus** [comment]
Ok! Eu desabilitei via SSH deletando a pasta do plugin dentro de `/wp-content/plugins`

Testei novamente, e agora o plugin está funcionando.
