### ISSUE TITLE
Shortcode

### ISSUE THREAD

**Issue by Eufranio** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#29]
Existe algum shortcode pra o menu?

**Comment by Luc45** [comment]
Eufranio, infelizmente ainda não. Como tudo no WooCommerce, a ordem de exibição da calculadora de frete é feita via filtros.

Por padrão, a cálculadora está hookada no filtro `woocommerce_before_add_to_cart_button`, mas você pode alterar isso, exemplo:

```php
add_filter('cfpp_hook_location', function() {
  return 'woocommerce_after_add_to_cart_button';
});
```
