### ISSUE TITLE
Erro em produtos com preço acima de mil reais e dias adicionais do prazo de entrega não são somados

### ISSUE THREAD

**Issue by GabrielS0uza** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#3]
Em produtos abaixo de mil reais o formulário é exibido e o cálculo é feito normalmente, porém em produtos acima desse valor a seguinte mensagem é mostrada:

 "Atenção
O cálculo de frete na página do produto não está sendo exibido aqui pois:
Preço inválido ou não preenchido.
(Não se preocupe, somente administradores do site vêem esta mensagem)"

Para os clientes o formulário é exibido, mas ao tentar calcular um alerta com a mensagem "undefined" aparece.

Outro problema é que o plugin não soma os dias adicionais do prazo de entrega.

Ambos os erros foram testados e comprovados no meu tema customizado e no twentyseventeen.

**Comment by Luc45** [comment]
Corrigido!
