### ISSUE TITLE
Erro após atualizar

### ISSUE THREAD

**Issue by lucianobeguelini** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#30]
Boa tarde!
Após atualizar o plug-in passou a ocorrer esse erro.
Já tentei remover e instalar denovo, entrei no ftp, removi a pasta do plugin, mas nao resolveu.
Ocorre o seguinte erro:
jquery-migrate.min.js? Ver = 1.4.1: 2 JQMIGRATE: Migrate está instalado, versão 1.4.1
/ wp-json / cfpp / v1 / calcular / 1584/15015200? Quantidade = 1 & variação_selecionada =: 1 Falha ao carregar o recurso: o servidor respondeu com um status de 500 ()
cfpp.js? ver = 1602005047: 59 - = CFPP retornou uma resposta de erro: Erro de banco de dados do WordPress Tabela 'semijoiasmaria.wp_correios_postcodes' não existe para uma consulta SELECT * FROM wp_correios_postcodes WHERE postcode = '15015200'; feito por require ('wp-blog-header.php'), wp, WP-> main, WP-> parse_request, do_action_ref_array ('parse_request'), WP_Hook-> do_action, WP_Hook-> apply_filters, rest_api_loaded, WP_REST_request-> serve , WP_REST_Server-> despachar, CFPP \ Rest-> calcular, CFPP \ Shipping \ ShippingCalculator-> processRestRequest, CFPP \ Shipping \ ShippingZone :: getFirstMatchingShippingZone, CFPP \ Shipping \ ShippingZone-> checkZoneLocationByState,

**Comment by Luc45** [comment]
Amigo, o plugin precisa do "WooCommerce" e do "WooCommerce Correios by Claudio Sanchez" para funcionar corretamente.
