### ISSUE TITLE
Dias de atraso definido no plugin dos correios

### ISSUE THREAD

**Issue by Gilbert-Marcone** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#32]
Plugin WooCommerce Correios Cáculo de Frete na Página do Produto, não adiciona os dias de atraso definido no plugin Claudio Sanches – Correios for WooCommerce, quando é inserido o cep na simulação de preço e tempo aproximado de entrega na página do produto.

**Comment by Luc45** [comment]
@Gilbert-Marcone Corrigido na versão 3.2, que vou lançar em breve... Obrigado
