### ISSUE TITLE
Plugin não trata produtos com variações

### ISSUE THREAD

**Issue by aandrade1234** [Luc45/WooCommerce-Correios-Calculo-de-Frete-na-Pagina-do-Produto#8]
Plugin não trata produtos com variações

**Comment by Luc45** [comment]
Amigo, o plugin foi re-escrito do zero essa semana -  essa funcionalidade está presente na nova versão.

Estou precisando de beta-testers para esta nova versão do plugin, se você puder ajudar a testar, seria ótimo!

Dá uma olhada: https://wordpress.org/support/topic/preciso-de-beta-testers-urgente/

Abraços!

**Comment by Luc45** [comment]
Fechado, resolvido nas versões mais recentes.
